# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Derick Yang
logo: /assets/img/derick-logo.png
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
permalink: /:categories/:year/:month/:title
collections:
  products:
    output: true
    permalink: /:title
  search:
    output: true
    permalink: /:title
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "circle.yml"
  - "vendor"
  - "exe"
