version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build site for minimized assets
          command: |
            git clone https://github.com/rbenv/rbenv.git ~/.rbenv
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
            export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

            rbenv install 2.4.1
            rbenv global 2.4.1
            gem install bundler
            gem install rainbow -v '2.2.1'
            bundle install
            gem install jekyll bundler
            bundle exec jekyll build

      - aws-s3/sync:
          from: ./_site/assets
          to: "s3://dyang108.github.io/"
          overwrite: true

workflows:
  push-assets:
    jobs:
      - build
