version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build site for minimized assets
          command: |
            bundle install
            gem install jekyll bundler
            bundle exec jekyll build

      - deploy:
          name: Copy assets to s3
          command: aws s3 sync _site/assets/* s3://dyang108.github.io/