version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run: bundle exec jekyll build

      - deploy: aws s3 sync _site/assets/* s3://dyang108.github.io/