version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build site for minimized assets
          command: gem install bundler && bundle exec jekyll build

      - deploy:
          name: Copy assets to s3
          command: aws s3 sync _site/assets/* s3://dyang108.github.io/